[package]
name = "rmsedit"
version = "0.1.0"
authors = ["Michael Hitchens <mdhitchens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "^0.34.3"
default-features = false
features = ["ttf"]
